{
    "name":"Odoo Multi Channel CRM",
    "version": '1.1.0',
    "sequence":10,
    "category": 'Other',
    'license': 'AGPL-3',
    "depends": ['mail', 'crm', 'sale'],
    "data":[
        'security/ir.model.access.csv',
        'views/multi_channel_crm_views.xml',
        'views/whatsapp_integration_views.xml',
        'views/gmail_integration_views.xml',
        'views/linkedIn_integration_view.xml',
        'views/instagram_integration_views.xml',
        'views/facebook_integration_views.xml',
        'views/kyc_feed.xml',
        'views/business_info_views.xml',
        'views/seller_offer_code_views.xml',
        'views/res_config_settings_views.xml',
        'views/channel_contact_mapping.xml',
        'views/channel_lead_mapping.xml',
        'views/crm_lead_views.xml',
        'views/res_partner_view.xml',
        'views/product_template_views.xml',
        'views/category_model_views.xml',
        'views/ai_agent_views.xml',
        'data/ir_cron_data.xml',
        'data/ir_sequence.xml',
        'views/menu.xml',
    ],
    'external_dependencies': {
        'python' : ['openai','google-genai'],
    },
    "pre_init_hook": "pre_init_check",
}
