from . import multi_channel_crm
from . import whatsapp_integration
from . import kyc_feed
from . import res_config_settings
from . import gmail_integration
from . import gmail_webhook_log
from . import channel_contact_mapping
from . import channel_lead_mapping
from . import crm_lead
from . import category_model
from . import linkedIn_integration
from . import instagram_integration
from . import facebook_integration
from . import twitter_integration
from . import product_template
from . import res_partner
